### ISSUE TITLE
introduce time data type

### ISSUE THREAD

**Issue by drmowinckels** [LCBC-UiO/noas#45]
been working on the questionnaires, and have found some instances where the column types in various data are not the same, and this is not detected since they are kept as text.

Need to introduce the time data format when we get the time.

https://stackoverflow.com/questions/42095121/how-do-i-convert-string-to-time-in-postgresql

**Comment by Athanasiamo** [comment]
best time format to implement is likely full hh:mm:ss, but without date connection, as this is the most meaningful for the data we have. We have some data where its only MM:SS, others with HH:MM, and then timeseries uses the full HH:MM:SS (some even with full datetime YYYY-MM-DDTHH:MM:SS)

Date is already implemented with ISO 8601 (sans time).

Perhaps its meaningful to have:
- Date YYYY-MM-DD
- Datetime YYYY-MM-DDTHH:MM:SSZ
- Time HH:MM:SS

I think something like that should cover all use cases I've seen in our data.

**Comment by drmowinckels** [comment]
date and datetime is handled by `date`.
