### ISSUE TITLE
failing when adding a new type of repeated group

### ISSUE THREAD

**Issue by drmowinckels** [LCBC-UiO/noas#51]
_noas.json should be able to handle a "repeated_group" key-value pairing, to make sure of similar repeated data being merged nicely if selected.

This is working great for MRI data.

I'm trying to add the same to the DBS data with a _noas.json like so

```json
{
    "table_type": "repeated",
    "repeated_group": "dbs"
}
```

But import is failing with an error for the meta-tables.
![image](https://user-images.githubusercontent.com/14014329/176612794-b5c288ca-f666-4f11-80ae-4a6fd210e6cf.png)

The data imports just fine without the repeated groups being specified in the json, so there is something there.

**Comment by Athanasiamo** [comment]
maybe the MRI gropu is hardcoded somewhere?

**Comment by drmowinckels** [comment]
cannot reproduce in test data. Will test again on the server.
